version: '2'

services:
  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile

  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile

  prom:
    image: prom/prometheus
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prom-data:/prometheus
    links:
      - collector
      - chat 
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana 
    volumes:
      - ./grafana-data:/var/lib/grafana
    links:
      - prom 
    ports:
      - 3000:3000
