version: '2'

services:
  collector:
    build:
      context: ./collector
      dockerfile: Dockerfile
    restart: always

  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
    restart: always

  prom:
    image: prom/prometheus
    command: -config.file=/etc/prometheus/prometheus.yml -storage.local.retention=2160h
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prom-data:/prometheus/data
    links:
      - collector
      - chat 
    ports:
      - 9090:9090
    restart: always
  
  grafana:
    image: grafana/grafana 
    volumes:
      - ./grafana-data:/var/lib/grafana
    links:
      - prom 
    ports:
      - 3000:3000
    restart: always
